### ISSUE TITLE
Persist caddy data in docker monolithic

### ISSUE THREAD

**Issue by bytestream** [supportpal/helpdesk-install#104]
Currently every time the container is restarted caddy requests new certificates. If you restart the container 5 times within a short period then LetsEncrypt rate limits you:
```
too many certificates (5) already issued for this exact set of domains in the last 168 hours
```

Suggested fix:

```yml
environment:
    XDG_CONFIG_HOME: /caddy/config
    XDG_DATA_HOME: /caddy/data
volumes:
    - caddy_volume:/caddy
```
